### PR TITLE
Modified PER test

### PR DESCRIPTION
**Pull request by yc-adi**
This PR is for a reliable PER test.

### CODE REVIEW

**Review by EricB-ADI — APPROVED** [review]

**Comment by yc-adi** [comment]
Results:
http://[10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-26-00_max32665_EvKit_V1.pdf](http://10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-26-00_max32665_EvKit_V1.pdf)
http://[10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-44-13_max32690_EvKit_V1.pdf](http://10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-44-13_max32690_EvKit_V1.pdf)
http://[10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-09-18_max32655_EvKit_V1.pdf](http://10.20.14.104:8000/per/pdf/?pdf=msdk-2023-02-16_15-09-18_max32655_EvKit_V1.pdf)

**Review by kevin-gillespie — CHANGES_REQUESTED** [review]
Can we archive the results in the workflow? Some of our existing workflows do this and it makes it easier to track.

**Review by kevin-gillespie — CHANGES_REQUESTED** [review]
It looks like we're getting an error.

https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4220042964

**Comment by yc-adi** [comment]
The running workflow code is the new one in the PR.
https://github.com/yc-adi/msdk_open/blob/dfbef3c6940461f9975d40642c98eaf9e2492087/.github/workflows/simple_per_test.yml#L219

But the log shows the script the new CI called is still the current one.
# board_per_test.sh 1_MSDK 2_BRD1 3_BRD2 4_CURR_TIME 5_CURR_JOB_FILE 6_CURR_LOG 7_all_in_one 8PKG 9PHY 10STEP   #

The new script in the PR is:
https://github.com/yc-adi/msdk_open/blob/dfbef3c6940461f9975d40642c98eaf9e2492087/.github/workflows/scripts/board_per_test.sh#L5
 
I tested the new PR in my repo. It worked.
https://github.com/yc-adi/msdk_open/actions/runs/4219687342

**Comment by kevin-gillespie** [comment]
Ok I see. The automated run being executed here is using an older version.

**Review by kevin-gillespie — APPROVED** [review]

**Pull request merged**
