### PR TITLE
Update VSCode project files + Makefile to v1.5.0

### PR DESCRIPTION
**Pull request by Jake-Carter**
This PR updates VS Code project files and core Makefiles to the latest VSCode-Maxim development files to be released as v1.5.0.

The following projects have had their core Makefile modified, and should be examined further.  I'm not sure if these should be included in this update.  If a project contains a Makefile it will get hit with the auto filter, so please check these below:
* `Examples/MAX32655/RF_Test` @EdwinFairchild 
* `Examples/MAX32655/Dual_core_sync/Dual_core_sync_riscv` @yc-adi 
* `Examples/MAX32655/Dual_core_sync/Dual_core_sync_arm` @yc-adi 
* `Examples/MAX78000/CameraIF_Debayer` @Jake-Carter

### CODE REVIEW

**Comment by EdwinFairchild** [comment]
The  RF testing application builds and works fine with this PR, unless I am supposed to be doing something specific in VS code?

**Review by yc-adi — APPROVED** [review]

**Comment by Jake-Carter** [comment]
> The RF testing application builds and works fine with this PR, unless I am supposed to be doing something specific in VS code?

Thanks, no just wanted to confirm the Makefile changes look ok.  Appreciate it!

**Review by EdwinFairchild — APPROVED** [review]

**Comment by yc-adi** [comment]
Yes, I successfully built it and ran on a MAX32655 board.

**Comment by Jake-Carter** [comment]
> Yes, I successfully built it and ran on a MAX32655 board.

Thanks

**Pull request merged**
