### PR TITLE
Add User Guide

### PR DESCRIPTION
**Pull request by Jake-Carter**
@Analog-Devices-MSDK/msdk_developers @Analog-Devices-MSDK/msdk_contributors @Analog-Devices-MSDK/msdk_maintainers 

This PR adds a universal User Guide for the MSDK.  The README has also been updated to point to it as the primary source of documentation.

It can be previewed from my fork here:  https://jake-carter.github.io/msdk/USERGUIDE/

The online copy is created with [mkdocs](https://www.mkdocs.org/) and deployed with Github Pages via a new ["Build Docs" action](https://github.com/Jake-Carter/msdk/blob/dev/userguide/.github/workflows/build-docs.yml).  The action also builds the Peripheral Driver Doxygen and packages it into the site under the [Peripheral Driver API section](https://jake-carter.github.io/msdk/USERGUIDE/#peripheral-driver-api).

The User Guide is maintained in a single Markdown file that can also be viewed directly:  https://github.com/Jake-Carter/msdk/blob/dev/userguide/USERGUIDE.md

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
Can we get some documentation describing the documentation?

**Comment by Jake-Carter** [comment]
> Can we get some documentation describing the documentation?

@kevin-gillespie Hey man I heard you like docs so I wrote some docs on how to get to the docs that tell you how to write and build the docs:

https://jake-carter.github.io/msdk/CONTRIBUTING/#contributing-documentation

There's a Python script in the repo now that you can use to build the static site locally.  Could probably update the action to use it but installing Doxygen is kind of a pain in the ass on the command-line

**Comment by kevin-gillespie** [comment]
What do you think about moving some of the files into the Documentation folder? It's nice to have the README in the root so we see it on the GitHub home page, but I think it would keep things better organized if we moved the rest to the Documentation folder.

**Comment by Jake-Carter** [comment]
> What do you think about moving some of the files into the Documentation folder? 

Agreed, see https://github.com/Analog-Devices-MSDK/msdk/pull/273/commits/251c7af29deabad3360cdf7718353037a5e75127

**Review by kevin-gillespie — APPROVED** [review]

**Review by sanjayjaroli — APPROVED** [review]
Great start for MSDK documentation!!

**Pull request merged**
