### PR TITLE
fix(PeriphDrivers): Add GPIO Chip Select Configuration for MAX32665 SPI driver

### LINKED ISSUE #396: MAX32665 SPI driver does not configure slave select.
MXC_SPI_Init() configures all of the pins except for slave select.

### PR DESCRIPTION
**Pull request by Brandon-Hurst**
### Description

fixes #396  . Add Chip Select configuration to MXC_SPI_Init using pre-existing me14_pins gpio cfg structs. SPI Example tested showing successful transactions and proper SPI Chip Select Behavior. 

image

Second image shows green LED1 on EVK, which indicates a successful run of the SPI example. 

#### Types
**fix** 

#### Scopes
**PeriphDrivers**

### CODE REVIEW

**Review by Jake-Carter — APPROVED** [review]
Thanks for picking this one up, looks good!

**Comment by Jake-Carter** [comment]
Hey @Brandon-Hurst just some formatter/linter errors in the auto checks.  See [Style Guide](https://analog-devices-msdk.github.io/msdk/CONTRIBUTING/#style-guide)

**Comment by Brandon-Hurst** [comment]
> Hey @Brandon-Hurst just some formatter/linter errors in the auto checks. See [Style Guide](https://analog-devices-msdk.github.io/msdk/CONTRIBUTING/#style-guide)

Thanks Jake, I fixed these with a new commit. Just a line of extra whitespace caused it to complain. Let me know if I need to squash and I can do that later to get this in.

**Comment by Jake-Carter** [comment]
Thanks Brandon, no worries on the squash.  We squash and merge into main

**Pull request merged**
