### PR TITLE
Fast Camera Display to Feather TFT

### PR DESCRIPTION
**Pull request by maximreza**
Update the Camera_IF example ( re-named CameraIF_DMA) to utilize two DMA channel to receive lines from camera, and send it to TFT.
A separate PR is submitted to update the MiscDrivers library as well

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
Can we close this?

**Comment by Jake-Carter** [comment]
> Can we close this?

Not yet, we're picking this up again

**Comment by Jake-Carter** [comment]
Addressed in https://github.com/Analog-Devices-MSDK/msdk/pull/437

**Pull request closed without merging**
