### PR TITLE
Added Python requirements file for Bluetooth tools

### PR DESCRIPTION
**Pull request by EricB-ADI**

### CODE REVIEW

**Review by EdwinFairchild — APPROVED** [review]

**Review by yc-adi — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
You can comment with the above command to let a runner format your committed files for you.

**Comment by EricB-ADI** [comment]
> You can comment with the above command to let a runner format your committed files for you.

Im going to close this PR, the changes are incorporated in a different PR

**Comment by sihyung-maxim** [comment]
Sounds good. Just FYI, the runner is doing its thing right now and will automatically push the formatted files once it's done (in 8-18 minutes). I think the action will just fail if you close the PR before it finishes, which is fine.

**Pull request closed without merging**
