### PR TITLE
Ci improvements

### PR DESCRIPTION
**Pull request by EdwinFairchild**
Redoing this, was getting all kinds of weird errors because of sub-modules.

This PR implements an updated launcher script that supports multiple MCUs. Currently MAX32655 and MAX32665 MAX32690

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
Are the Examples modifications merged from MAX32655?

**Comment by EdwinFairchild** [comment]
Tested it , OOB works fine between ME17 and ME14

**Comment by kevin-gillespie** [comment]
I figured it was a merge, just wanted to make sure. Not sure if we've missing anything but I'll take a closer look.

**Comment by kevin-gillespie** [comment]
There are some pretty minor differences. We should also update the READMEs to mostly match.
[three-way-merge.txt](https://github.com/Analog-Devices-MSDK/msdk/files/10036081/three-way-merge.txt)

**Review by yc-adi — APPROVED** [review]

**Pull request closed without merging**
