### PR TITLE
Adding the SPI_MasterSlave example to all micros with EV Kits that support it.

### PR DESCRIPTION
**Pull request by Jacob-Scheiffler**

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Most of the file changes in this PR are due to the clang-format-run workflow formatting the third-party libraries. However, that workflow should have excluded all the third-party library files, so something is off. Need to investigate.

**Comment by Jake-Carter** [comment]
> Most of the file changes in this PR are due to the clang-format-run workflow formatting the third-party libraries. However, that workflow should have excluded all the third-party library files, so something is off. Need to investigate.

@sihyung-maxim @Jacob-Scheiffler revert https://github.com/Analog-Devices-MSDK/msdk/pull/264/commits/4f273f236ac41eeffb41ba22f7bfbf6989211b3b, merge with master, then re-run the formatter.  

The formatter was updated to ignore submodule files in https://github.com/Analog-Devices-MSDK/msdk/pull/234, so this branch is probably just a little behind

**Review by sihyung-maxim — APPROVED** [review]

**Review by lorne-maxim — APPROVED** [review]

**Pull request merged**
