### PR TITLE
fix(CMSIS): MSDK-1179: Fix ADC_LIMIT CH Limit Enable field locations for MAX32665, MAX32680, and MAX78000

### PR DESCRIPTION
**Pull request by sihyung-maxim**
Fixed ADC_LIMIT Channel HI/LO Limit Enable field locations.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Step 1: Update the affected SVD file and push it into your branch.
Step 2: Open a PR and comment `/generate-register-files` to generate and commit the new register files.

@Suraj-Ajjampur and @Vignesh (Vignesh isn't in the GitHub org).

**Comment by sihyung-maxim** [comment]
Whoops, accidentally retriggered the workflow.

**Comment by Suraj-Ajjampur** [comment]
[3:50 PM] Vu, Hiep

Design:

ADC_LIMIT[31] - RFU

ADC_LIMIT[30] - High Limit Enable

ADC_LIMIT[29] - Low Limit Enable

ADC_LIMIT[28:24]] - ch_sel

ADC_LIMIT[23:22] - RFU

ADC_LIMIT[21:12] - ch_hi_limit

ADC_LIMIT[11:10] - RFU

ADC_LIMIT[9:0] - ch_lo_limit

Got these bit fields from Hiep Vu from the Design team. 
I think the old bit fields are correct

**Pull request closed without merging**
