### PR TITLE
ME14/18 examples

### PR DESCRIPTION
**Pull request by EdwinFairchild**
Bring ME14 and ME18 examples up to current state of development.
Ci- will not only run ALL mcu test if changes to Cordio Libraries, PHY where made.
If changes to an example where made it  will only run test on that device. 

Some issue with ME14 persists but we will tackle that in a future PR. A temp fix has been applied

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
This in project.mk will work.

```bash
AUTOSEARCH = 0

SRCS += main.c
SRCS += stack_fit.c
SRCS += fit_main.c
```

This will fail
```bash
AUTOSEARCH = 0

SRCS += stack_fit.c
SRCS += fit_main.c
SRCS += main.c
```

**Comment by yc-adi** [comment]
https://github.com/Analog-Devices-MSDK/msdk/pull/313#issuecomment-1362216688
Did we find what caused this difference?

**Comment by kevin-gillespie** [comment]
> [#313 (comment)](https://github.com/Analog-Devices-MSDK/msdk/pull/313#issuecomment-1362216688) Did we find what caused this difference?

Nearly there.

**Comment by kevin-gillespie** [comment]
> > [#313 (comment)](https://github.com/Analog-Devices-MSDK/msdk/pull/313#issuecomment-1362216688) Did we find what caused this difference?
> 
> Nearly there.

Actually no, I'm not. I thought I was on to something but we're still trying to figure out the memory corruption problem. We can merge this in and create another PR to debug.

**Review by kevin-gillespie — APPROVED** [review]

**Review by yc-adi — APPROVED** [review]

**Pull request merged**
