### PR TITLE
fix(PeriphDrivers,CMSIS): SBISYS-216: Fix typos in SPI Rx Request Select, new SVD file for MAX32690

### PR DESCRIPTION
**Pull request by Vitorbnc**
### Description

* Fixed typos in SPI request select for SPI3 and SPI4. It was preventing SPI transactions from working in DMA mode for MAX32690GWE+
* Added updated SVD file for debugging MAX32690GWE+. Peripherals SPI3 and SPI4 were missing.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Nice catch. I've updated our SVD scripts to include SPI3 and SPI4.

**Review by sihyung-maxim — APPROVED** [review]

**Comment by Vitorbnc** [comment]
> Nice catch. I've updated our SVD scripts to include SPI3 and SPI4.
Thank you!

**Review by Jake-Carter — APPROVED** [review]
Thanks @Vitorbnc

**Pull request merged**
