### PR TITLE
fix(CMSIS): Rename SYS registers with TX/RX LDO to RF/BB LDO for MAX32655 and MAX32680

### PR DESCRIPTION
**Pull request by kevin-gillespie**
Renaming TX LDO to RF LDO.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
The generate registers workflow references the SVD scripts in msdk-internal, and there were some changes made to the ME17B SVD scripts recently which broke the workflow. I just fixed it.

**Comment by sihyung-maxim** [comment]
Updated the generate-registers workflow to catch runtime errors from all the python scripts. The runner should respond with a "confused" emoji when an SVD file isn't formatted correctly. This feature won't be implemented until the changes are pushed into main.

Thanks for being the first guinea pig for the workflow.

**Comment by sihyung-maxim** [comment]
> Updated the generate-registers workflow to catch runtime errors from all the python scripts. The runner should respond with a "confused" emoji when an SVD file isn't formatted correctly. This feature won't be implemented until the changes are pushed into main.
> 
> Thanks for being the first guinea pig for the workflow.

Also noticed GitHub's checkout action doesn't always checkout the latest changes if you repeatedly run the workflow. I added a workaround step to ensure the runner's workspace is always updated by running git pull.

**Comment by Jake-Carter** [comment]
@sihyung-maxim build errors seem to be legit.  If you pull in the latest build workflow the output should be a little more readable

**Comment by EricB-ADI** [comment]
@Jake-Carter @sihyung-maxim Is this still active?

**Comment by Jake-Carter** [comment]
> @Jake-Carter @sihyung-maxim Is this still active?

Not sure.  @sihyung-maxim?

**Comment by EricB-ADI** [comment]
I'm going to close this PR. It is updated in #680

**Pull request closed without merging**
