### PR TITLE
Sending address with each data packet.

### PR DESCRIPTION
**Pull request by kevin-gillespie**

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
This changes the OTA protocol to send a 4 byte address at the start of each data packet. There is additional overhead with this, but it is much more robust.

The current implementation breaks down when the data is delivered to the application layer out of order. We can correct this by using write requests instead of commands, but this drastically reduces the transfer speed.

Sending the address allows us to send write commands, since they can be delivered to the application layer in any order. 

TODO: Update other targets, update phone app, update BLE PyDex

**Comment by yc-adi** [comment]
@EdwinFairchild Recently there are several BLE Examples Test failures.

**Comment by yc-adi** [comment]
Thanks for the update.
I use awk to get port number like:
export devUart3Serial_1=/dev/tty"$(ls -la /dev/serial/by-id | grep -n $DevKitUart3Sn_1 | awk -F tty '{print $2}')".
BTW, what's the link for the PR?

**Review by yc-adi — APPROVED** [review]

**Review by EdwinFairchild — APPROVED** [review]

**Comment by kevin-gillespie** [comment]
@EdwinFairchild 

We'll have to make sure the various client apps are updated to match this.

**Pull request merged**
