### PR TITLE
NewHaven display support for MAX78002 EvKit. Replaced sprintf() with snprintf() function

### PR DESCRIPTION
**Pull request by vicloginov**

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Please update your fork with the latest changes in main. Checks should all pass now once you do that.

**Review by lorne-maxim — APPROVED** [review]

**Review by Jake-Carter — COMMENTED** [review]
Looks good, I will move includes to board.h and update project.mk files.

Lost access to previous forks when we went public, @vicloginov can you share your private MSDK fork with me directly?

**Comment by Jake-Carter** [comment]
Migrating to https://github.com/Analog-Devices-MSDK/msdk/pull/193

**Pull request closed without merging**
