### PR TITLE
fix(ThirdParty,Examples): Add missing dependencies to LVGL makefiles

### PR DESCRIPTION
**Pull request by lorne-maxim**
Add the missing statements needed for all files in the Libraries/LVGL/lvgl/src/extra directories.
Disable Flash ECC in the MAX32672 Flash example.  It uses 32-bit writes which will not work when ECC is enabled.

### CODE REVIEW

**Review by Jake-Carter — CHANGES_REQUESTED** [review]
I'd suggest using `IPATH` instead of `CFLAGS += -I...`

**Comment by lorne-maxim** [comment]
I thought it was strange that the other makefiles weren't using IPATH.  I just stuck with the style used by the others, though.  What do you think?  Should we rework all the makefiles in LVGL?

**Comment by Jake-Carter** [comment]
Eh...  at this point that's probably a better cleanup task for a later date.  If they all use this convention this'll work

**Review by Jake-Carter — APPROVED** [review]

**Comment by lorne-maxim** [comment]
That's what I was hoping you'd say!

**Pull request merged**
