### PR TITLE
build(Other): Add Support for Native Windows Builds, Add `RISCV_LOAD` Support for MAX78000 and MAX78002

### PR DESCRIPTION
**Pull request by Jake-Carter**
### Description

This removes dependencies on Linux utilities (`sed`, `cut`, `rmdir`, etc.) for builds on native Windows.  Now, the only requirement to run a native Windows build is a native make executable.

The primary driver behind this was our upcoming integration with the ONE IDE installer.  (see https://jira.analog.com/browse/DEVTOOLS-96)

**How to Review:** Check out this branch and run functional tests of your choice in your environment of your choice.

##### MSYS2

Note: "MSYS2" = existing environment in MSDK.  

- [x] : AI85 Hello_World (MSYS2) - *PASS*
- [x] : AI85 Hello_World_Cpp (MSYS2) - *PASS*
- [x] : AI85 Coremark (MSYS2) - *PASS*
```serial
SystemCoreClock 100000000
I-Cache enabled
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 13792893
Total time (secs): 13.792893
Iterations/Sec   : 290.004416
Iterations       : 4000
Compiler version : GCC10.3.1 20210824 (release)
Compiler flags   : 
Memory location  : STATIC
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x65c5
Correct operation validated. See README.md for run and reporting rules.
CoreMark 1.0 : 290.004416 / GCC10.3.1 20210824 (release)  / STATIC

```

##### ONE IDE

"ONE IDE" = building _only_ with make supplied by the ONE IDE.

- [x] : AI85 Hello_World(ONE IDE) - *PASS*
- [x] : AI85 Hello_World_Cpp (ONE IDE) - *PASS*
- [x] : AI85 Coremark (ONE IDE) - *PASS*
```serial
SystemCoreClock 100000000
I-Cache enabled
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 13792893
Total time (secs): 13.792893
Iterations/Sec   : 290.004416
Iterations       : 4000
Compiler version : GCC10.3.1 20210824 (release)
Compiler flags   : 
Memory location  : STATIC
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x65c5
Correct operation validated. See README.md for run and reporting rules.
CoreMark 1.0 : 290.004416 / GCC10.3.1 20210824 (release)  / STATIC
```

#### Backwards Compatibility

The following projects were functionally tested from our existing MSYS2 environment with the changes proprosed in this PR.  This confirms backwards compatibility with existing/legacy projects that use combined .elfs (`Makefile`/`Makefile.ARM`/`Makefile.RISCV`)

- [x] : AI87 ImageNet-RISCV - *PASS*
```serial
---- Opened the serial port COM20 ----

*** CNN Inference Test imagenet-riscv ***

*** PASS ***

Approximate inference time: 35155 us
```
- [x] : AI85 mnist-riscv - *PASS*
```serial
*** CNN Inference Test ***

*** PASS ***

Approximate inference time: 1418 us

Classification results:
[ -77992] -> Class 0: 0.0%
[  93377] -> Class 1: 0.0%
[  45484] -> Class 2: 0.0%
[  29850] -> Class 3: 0.0%
[ -36248] -> Class 4: 0.0%
[-130974] -> Class 5: 0.0%
[-272399] -> Class 6: 0.0%
[ 416616] -> Class 7: 100.0%
[-148783] -> Class 8: 0.0%
[  25073] -> Class 9: 0.0%
```
#### `RV_ARM_Loader` Functional Tests

The RV_ARM_Loader does its job.  It loads the source code and starts the RISC-V core correctly.  Our peripheral drivers themselves need some work for the RISC-V core.

- [x] : AI85 RV_ARM_Loader + Hello_World - *PASS w/ caveat*
  - The example runs, but the blink rate is too slow.  There is an issue with the MXC_Delay implementation for the RISC-V core that needs to be addressed in a separate PR.
```serial
ARM: RV_ARM_Loader
Hello World!
count : 0
count : 1
count : 2
count : 3
```
- [x] : AI85 RV_ARM_Loader + Hello_World_Cpp - *PASS w/ caveat*
  - Slow blink-rate, see above.
```serial
ARM: RV_ARM_Loader
C++ Hello World Example
Number of blinks: 1
Number of blinks: 2
Number of blinks: 3
Number of blinks: 4
```
- [x] AI85 RV_ARM_Loader + Coremark - *Pass w/ caveat*
  - Coremark builds, flashes, and runs for the RISC-V core.  But the results are incorrect.  Source code of the example needs some tweaking for RISC-V.
```serial
ARM: RV_ARM_Loader


SystemCoreClock 443432905
I-Cache enabled
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 19726619
Total time (secs): 
Iterations/Sec   : 
Iterations       : 4000
Compiler version : GCC12.2.0
Compiler flags   : 
Memory location  : STATIC
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x65c5
Correct operation validated. See README.md for run and reporting rules.
CoreMark 1.0 :  / GCC12.2.0  / STATIC
```

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [x] Description of changes and all other relevant information.
- [x] (Optional) Link any related Github issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [x] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
This is complete for M4-core builds targeted via `gcc.mk`.  Adding WIP for the RISC-V builds that have some other `sed` dependencies scattered around that I need to address.

**Comment by andrewmclachlanadi** [comment]
Awesome. Thanks for the update. Tag @mharringADI. Will give it a try out.

**Comment by andrewmclachlanadi** [comment]
Thanks!

**Review by andrewmclachlanadi — APPROVED** [review]

**Comment by Jake-Carter** [comment]
Status update:  This is almost ready.  I had to go down a really deep rabbit hole for the RISC-V loader, which was unexpected...  but it works now.  Remaining items:

- [ ] : Develop powershell equivalent of .map file parser
- [ ] : Port AI85 RISCV loader to AI87
- [ ] : Clean out old examples that use the `sed` makefiles (Mostly CNN RISC-V projects)

**Review by sihyung-maxim — APPROVED** [review]
The prophesized native windows build

**Review by Jacob-Scheiffler — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
The new Build scope was also merged into main if you want to add that to your PR title.

**Comment by Jake-Carter** [comment]
@andrewmclachlanadi FYI the following projects still require some Unix utilities.  I'm leaving them for now since they represent legacy projects in our build tests.  The MSDK repo isn't ready to remove them just yet, but they'll be updated before the next release.

* `Examples/MAX32655/Hello_World-riscv`
* `Examples/MAX32680/Hello_World-riscv`
* `Examples/MAX78000/CNN/faceid_evkit-riscv`
* `Examples/MAX78000/CNN/kws20_demo-riscv`
* `Examples/MAX78000/CNN/mnist-riscv`
* `Examples/MAX78002/CNN/imagenet-riscv`

**Comment by Jake-Carter** [comment]
> The prophesized native windows build

and there was much rejoicing

@Analog-Devices-MSDK/msdk_developers FYI this is merged

**Pull request merged**
