### PR TITLE
feat(Boards): Update LP board settings for MAX32655 RevB1

### PR DESCRIPTION
**Pull request by kevin-gillespie**
Updating MAX32655 LP settings for revision B1.

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
Ok I modified that function to ```GPIO_Init()``` that is called at Board_Init. 

@Jacob-Scheiffler The VDDIO/VDDIOH settings still don't seem correct. I'm measuring ~20 uA through VREGI when we're in standby mode. I think this should be close to 0.

**Review by lorne-maxim — APPROVED** [review]

**Comment by Jacob-Scheiffler** [comment]
> TODO: We'll have to set the VCOREB voltage to 0.81 whenever we enter standby/backup mode. We will probably have to raise the voltage back once we exit standby/backup.

You are correct. I was seeing Standby measurements around 5uA, although it varied slightly depending on VCOREB/VREGO_B settings.

**Comment by kevin-gillespie** [comment]
Tom suggested we look at the RTC oscctrl register. 

MXC_RTC->oscctrl = 0x9, but should be 0 to minimize RTC current consumption.

**Comment by Jake-Carter** [comment]
@lorne-maxim @Jacob-Scheiffler any idea what the status of this one is?  Good to merge or do we need to take a deeper look at the MXC_RTC->oscctrl setting?

**Comment by Jacob-Scheiffler** [comment]
@jake-carter No idea where Kevin left off with this. I haven't heard anything from design about any further LP testing for the ME17B either.

**Pull request closed without merging**
