### PR TITLE
Added dtm_sweep.py

### PR DESCRIPTION
**Pull request by tim-magnusen**
Created DTM sweep test based on conn_sweep.py framework.

### CODE REVIEW

**Review by yc-adi — APPROVED** [review]

**Review by EdwinFairchild — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
The SVD action will fail if the source branch of a PR is from a fork. There's a fix for this merged into main already, but this check isn't important for this PR as there were no register or SVD files that were changed.

**Comment by kevin-gillespie** [comment]
@EricB-ADI @kevin-gillespie

**Comment by EricB-ADI** [comment]
@kevin-gillespie It is effectively the same as conn_sweep_rsl15. @tim-magnusen did you plan on using any non MAX32 boards as a master such as a nordic? If you want I can add an option to use the vendor specific tx test instead of the vendor specific end test, so the nordic boards will still work.

**Comment by EricB-ADI** [comment]
@tim-magnusen The conn_sweep_rsl15 also uses DTM, it was named incorrectly. That will be changed soon. For now, I will merge this so you can use it. I will integrate options to use the end test vendor specific command so you can get more verbose information for receiver testing on MAX32 boards.

**Pull request merged**
