### PR TITLE
Examples/MAX32680/Hello_World-riscv works on both 'make' and 'make PR…

### PR DESCRIPTION
**Pull request by yc-adi**
Applied the same fix of MAX32655/Hello_World-riscv Makefile on this project.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Please update your fork with the latest changes in main. The checks should all pass now.

**Comment by yc-adi** [comment]
Updated my fork with the latest changes in main.

**Comment by lorne-maxim** [comment]
> Should the log.txt file in Examples/MAX32655/Hello_World-riscv also be deleted? It's still present in the SDK.
> 
> Looks good though. Please wait until the ME13 examples are sorted out and the workflows are updated before merging so all the checks can pass. I'll approve once those are working again.

Agreed.  This file should probably be deleted.

**Review by sihyung-maxim — APPROVED** [review]

**Pull request merged**
