### PR TITLE
style(Other): Add Apache License 2.0

### PR DESCRIPTION
**Pull request by sihyung-maxim**
### Description

This PR adds the Apache 2.0 License to the SDK. This only applies to files with the permissive, open-source version of the Maxim Integrated Copyright notice.

THe ME13 and ME55 files are ignored in this PR as they will be updated in a separate PR.

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [x] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Jacob and I did a spot check on all file types (.cpp, .c, .h, .s, .S, .ld, .mk, Makefiles, .py, and .txt).

**Comment by Jake-Carter** [comment]
Looks like we need to blacklist `SecureROM_BL_Host/test_images` for the format checker or `// clang-format off` / `//clang-format on` the contents of the blinkled file

**Comment by sihyung-maxim** [comment]
The labeler is getting confused because GitHub only goes through the first 3000 files of a PR. The rest of the files are ignored.

**Review by Jake-Carter — APPROVED** [review]

**Review by lorne-maxim — APPROVED** [review]
Looks OK to me.  I do see a *.Tariq file that probably needs to be deleted.

**Pull request merged**
