### PR TITLE
Generate_Register_Files Workflow Test.

### PR DESCRIPTION
**Pull request by sihyung-maxim**
This PR tests the new Generate_Register_Files workflow, and adds a README on how to use this workflow in .github/workflows.

### CODE REVIEW

**Comment by sihyung-maxim** [comment]
Test 1: Changed a peripheral SVD file linked to a single Part.

[Success] https://github.com/Analog-Devices-MSDK/msdk/actions

**Comment by sihyung-maxim** [comment]
Test 2: Changed a peripheral SVD file linked to multiple parts.

[Success] https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4407561100/jobs/7721393688
[Results]  https://github.com/Analog-Devices-MSDK/msdk/pull/487/commits/e842fabb11208bb5ffa17242dc68920c833f7df6#diff-e3e77a00e376ce6f58396d8f5ca1d757f3f03d2295b15205d8aed36e23c3b2d7

**Comment by sihyung-maxim** [comment]
Test 3: Updated a peripheral SVD file, but only generate register files for a single part.

[Success] https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4407620155
[Results]  https://github.com/Analog-Devices-MSDK/msdk/pull/487/commits/463cd050e0a15aa1138dd7ef2082f4954ed3ef67

**Comment by sihyung-maxim** [comment]
Test 4: Updated a peripheral SVD file, but only generate register files for a single part.

[Success] https://github.com/Analog-Devices-MSDK/msdk/actions/runs/4407701608/jobs/7721724811
[Results]  https://github.com/Analog-Devices-MSDK/msdk/pull/487/commits/71143849bca6c8e3135275488e6a66dab19c656f

**Review by kevin-gillespie — APPROVED** [review]

**Pull request merged**
