### PR TITLE
Remove CRC files for MAX32672

### LINKED ISSUE #527: MAX32672 (ME17) Has "crc.h"
Screenshot (154)

Within any of the MAX32xxx peripheral drivers, the crc.h file includes crc_regs.h that cannot be found anywhere.

### PR DESCRIPTION
**Pull request by Jake-Carter**
CRC functionality for the MAX32672 exists within the CTB peripheral block.  The CRC files were unused and misleading, so they've been removed.

Users looking for CRC functionality should check the [CTB peripheral block documentation](https://analog-devices-msdk.github.io/msdk/Libraries/PeriphDrivers/Documentation/MAX32672/group__ctb.html).  CRC functions exist under `MXC_CTB_CRC_xxx` function headers.

Resolves #527

### CODE REVIEW

**Comment by Jake-Carter** [comment]
@EdwinFairchild `RF_Test` is missing a semicolon as of https://github.com/Analog-Devices-MSDK/msdk/pull/481

Can you fix the build and push to this branch?  Thanks

**Comment by EdwinFairchild** [comment]
> @EdwinFairchild `RF_Test` is missing a semicolon as of #481
> 
> Can you fix the build and push to this branch? Thanks

how the heck

**Comment by EdwinFairchild** [comment]
> ```shell
> git remote add jake git@github.com:Jake-Carter/msdk.git
> git fetch jake
> git checkout remotes/jake/gh-527 -b yourbranch
> git push jake yourbranch:gh-527
> ```

Solid info thanks!!!

**Comment by Jake-Carter** [comment]
@sihyung-maxim looks like verify registers/SVD doesn't work on forks?

**Review by EdwinFairchild — APPROVED** [review]

**Comment by sihyung-maxim** [comment]
> @sihyung-maxim looks like verify registers/SVD doesn't work on forks?

Not sure why the job failed for this fork even though it passed in your other fork for PR #521. I've specified the context of the checkout action to make sure it checks out the PR's repo (fork) and head of the source branch instead of letting the runner default those locations.

**Pull request merged**
