### PR TITLE
Explicitly Use clang-format-14

### PR DESCRIPTION
**Pull request by Jake-Carter**
Replace `Empty` values in .clang-format, which my result in variations between versions of the tool.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
@kevin-gillespie @EdwinFairchild 

The clang-format workflow should now match local runs with version 14.

Wall-E has been updated with v14 and a `CLANG_VERSION` variable has been added to the scripts.

See https://github.com/Analog-Devices-MSDK/msdk/pull/156/commits/ee88adcddc99d3e95f3c2f0831303927ae6245fc for latest auto-run

**Comment by EdwinFairchild** [comment]
running clang-format --version on wall-e yields still v12. ? Or is it like another instance for github actions?

**Comment by Jake-Carter** [comment]
> running clang-format --version on wall-e yields still v12. ? Or is it like another instance for github actions?

Use `clang-format-14 --version`.  

We can have the scripts call a specific version binary, but we can also symlink `clang-format` to `clang-format-14` for convenience on wall-e (which I have not done)

**Comment by EdwinFairchild** [comment]
ah yeah i see the script now, idk why  i thought there was a space there and version was being passed as an argument.

**Review by lorne-maxim — APPROVED** [review]

**Review by EdwinFairchild — APPROVED** [review]

**Pull request merged**
