### PR TITLE
feat(BLE,Examples): Add Cordio API to get Bluetooth MAC address, trace output of MAC address and advertising name for MAX32655, MAX32665, MAX32690

### PR DESCRIPTION
**Pull request by EdwinFairchild**
This fixes random MAC address issue on ME17 and I think it is helpful to print the MAC address on start up. Helped me find a bug where all ME17 had different MAC addresses due to some junk value always being put in there.

### CODE REVIEW

**Comment by EdwinFairchild** [comment]
@yc-adi @EricB-ADI 
❤️

**Comment by EricB-ADI** [comment]
Is the or unique enough?

**Comment by EdwinFairchild** [comment]
those are actually the x,y coordinates on the wafer

**Comment by EricB-ADI** [comment]
> those are actually the x,y coordinates on the wafer

Hmm did not know that

**Review by yc-adi — APPROVED** [review]

**Pull request merged**
