### PR TITLE
chore(Other): Remove old Maxim license from all files

### PR DESCRIPTION
**Pull request by sihyung-maxim**
### Description

This PR removes the old Maxim license.

### Checklist Before Requesting Review

- [x] PR Title follows correct guidelines.
- [ ] Description of changes and all other relevant information.
- [ ] (Optional) Link any related GitHub issues [using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
- [ ] (Optional) Provide info on any relevant functional testing/validation.  For API changes or significant features, this is not optional.

### CODE REVIEW

**Comment by Jake-Carter** [comment]
We need to remove the old copyrights entirely now?

**Review by lorne-maxim — APPROVED** [review]

**Comment by lorne-maxim** [comment]
> We need to remove the old copyrights entirely now?

Yes.  It has been a nightmare getting all this straight.  Big props to Sihyung for taking it on!

**Comment by sihyung-maxim** [comment]
> We need to remove the old copyrights entirely now?

I plan on sending the updated copyright formats to the team once this change is approved.

**Review by Jake-Carter — APPROVED** [review]

**Pull request merged**
