### PR TITLE
Cordio dtm schedule

### PR DESCRIPTION
**Pull request by kevin-gillespie**
This will schedule the RX due time of the packets when using DTM. This will minimize the setup time based on the length of the previously received packet. 

We will have to follow this up with a RF-PHY PR to remove any additional scheduling offsets being made.

### CODE REVIEW

**Review by victor-levi-maxim — APPROVED** [review]

**Comment by tim-magnusen** [comment]
In the simple_per_test, the 'loss' is set to -17.4, where did this number come from?  Ying and I measured -16.4dB loss from MExx to SA.  Nordig at txPower=0 measures +0.7dBm.  For an effective -30dBm at MExx input with Nordig set to txPower=0, the attenuation should be set to 14.3dB (or rounded to 14.5dB).

All of the PER results are 100%, is this a test setup issue or did it really fail?

**Comment by kevin-gillespie** [comment]
This is going to be difficult to verify because it will require changes to physical layer. For what it's worth, I ran a sweep over packet length at my desk.
[results.csv](https://github.com/Analog-Devices-MSDK/msdk/files/10747409/results.csv)

**Comment by EdwinFairchild** [comment]
looked at the failed BLE test and the client side gets into a PAL assert
```

**Comment by EdwinFairchild** [comment]
Looked at the failed elfs and its the client in OTAC/S test that gets into a PAL assert trap

```


0x10023dfa in PalSysAssertTrap () at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_sys.c:163
163	/home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_sys.c: No such file or directory.
(gdb) Quit
(gdb) bt
#0  0x10023dfa in PalSysAssertTrap () at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/platform/targets/maxim/max32655/sources/pal_sys.c:163
#1  0x100228d0 in WsfAssert (pFile=pFile@entry=0x1006fe9f "/home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/wsf/sources/targets/baremetal/wsf_buf.c", line=line@entry=398)
    at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/wsf/sources/targets/baremetal/wsf_assert.c:63
#2  0x10022ab4 in WsfBufFree (pBuf=pBuf@entry=0x20007170) at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/wsf/sources/targets/baremetal/wsf_buf.c:398
#3  0x1000045e in datcSendBlock (connId=<optimized out>, address=121920, len=120, pData=0x10043650 <_binary_fw_update_bin_start+121920> "\rЫ\372pG") at datc_main.c:667
#4  0x10000c3e in datcProcMsg (pMsg=0x20006fe8) at datc_main.c:1016
#5  DatcHandler (event=<optimized out>, pMsg=0x20006fe8) at datc_main.c:1329
#6  0x100232e4 in wsfOsDispatcher () at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/wsf/sources/targets/baremetal/wsf_os.c:299
#7  0x1002335e in WsfOsEnterMainLoop () at /home/btm-ci/Workspace/btm-ci-github-runner0/_work/msdk/msdk/Libraries/Cordio/wsf/sources/targets/baremetal/wsf_os.c:398
#8  0x100003fe in main () at main.c:269
(gdb)
```

**Comment by kevin-gillespie** [comment]
WsfBuf uses a magic value to determine if the buffer is free. 

```
/* Magic number used to check for free buffer. */
#define WSF_BUF_FREE_NUM            0xFAABD00D

...

#if WSF_BUF_FREE_CHECK_ASSERT == TRUE
      WSF_ASSERT(p->free != WSF_BUF_FREE_NUM);
      p->free = WSF_BUF_FREE_NUM;
#endif
```
If that value happens to align just right, then it will match the start of the buffer when we execute the free. 

```
(gdb) up
#3  0x1000045e in datcSendBlock (connId=<optimized out>, address=121920, len=120, pData=0x10043660 <_binary_fw_update_bin_start+121920> "\rЫ\372pG") at datc_main.c:667
667	    WsfBufFree(addrData);
(gdb) print/x address
$4 = 0x1dc40
(gdb) x/32x addrData
0x20007060:	0x0001dc40	0xfaabd00d	0x00004770	0x88d34a07
0x20007070:	0x42938912	0x1a98d302	0x4770b280	0x88884903
0x20007080:	0xfa131a80	0xb280f080	0xbf004770	0x20002f10
0x20007090:	0x4b06b508	0xb11368db	0x7c104a04	0x22014798
0x200070a0:	0x20024903	0xfea0f001	0xbf00bd08	0x20002f10
0x200070b0:	0x20002f20	0x4604b538	0x89134a0e	0x889018c1
0x200070c0:	0xdd014281	0xb2841ac0	0xd8082cff	0x68294d09
0x200070d0:	0x44194622	0xf0012002	0x816cfedb	0x78e7faff
(gdb) x/x pData
0x10043660 <_binary_fw_update_bin_start+121920>:	0xfaabd00d
```
What are the chances!?!

**Comment by EdwinFairchild** [comment]
apparently if there is a non zero chance BTM team  will get the winning ticket

**Comment by kevin-gillespie** [comment]
@tim-magnusen 
We've addressed some issues with the PER test. The results we have now look better.

**Review by tim-magnusen — APPROVED** [review]

**Pull request merged**
